### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by PedroKim** [pkupchick/boredombreakers#1]
#### 1st MVP
- [ ] put a space in between - and "Setup", so that it becomes a bullet point
#### General
- [ ] besides hosting on heroku and Production README, there should be five mvps to be done.
- [ ] Include profile for one of the MVPs and create a section for bonus and list Google Maps integration and search

**Comment by PedroKim** [comment]
## 7) Production README

## Bonus
- Google Maps APi
- Search

**Comment by pkupchick** [comment]
Fixed MVP List.
